$random = {
   "byte"    => "(byte)rand.nextInt(256)",
   "short"   => "(short)rand.nextInt(32000)",
   "int"     => "rand.nextInt()",
   "long"    => "rand.nextLong()",
   "boolean" => "rand.nextBoolean()",
   "float"   => "rand.nextFloat()",
   "double"  => "rand.nextDouble()",
   "char"    => "(char)rand.nextInt()"

}

$wrap = {
   "byte"    => "Byte",
   "short"   => "Short",
   "int"     => "Integer",
   "long"    => "Long",
   "boolean" => "Boolean",
   "float"   => "Float",
   "double"  => "Double",
   "char"    => "Character"
}

$zero = {

   "byte"    => "0x00", 
   "short"   => "0",
   "int"     => "0",
   "long"    => "0L",
   "boolean" => "false",
   "float"   => "0.0f",
   "double"  => "0.0d",
   "char"    => "'\\u0000'"
}

def make file, primitives, suffix
  template = nil
  begin
    f        = File.open(file) 
    template = f.read
  ensure
    f.close if f
  end

  primitives.each {|primitive|
    n = template.gsub("<<Type>>"   , primitive)
    n =        n.gsub("<<Name>>"   , primitive.capitalize)
    n =        n.gsub("<<Warning>>", "/* DO NOT EDIT THIS FILE, IT IS GENERATED! */") 
    n =        n.gsub("<<Random>>" , $random[primitive])
    n =        n.gsub("<<Wrap>>", $wrap[primitive])
    n =        n.gsub("<<0>>", $zero[primitive])
    
    file_name = "src/java/primitive/collection/#{primitive.capitalize}#{suffix}.java"

    File.open(file_name, "w") { |f|
      f.print(n)
    }

  }

end

if $0 == __FILE__
  template = nil

  all = %w{
    byte
    short
    int
    long
    boolean
    float
    double
    char
  }

  no_bool = all - ["boolean"]

  make("template/List.java.template", all, "List")
  make("template/StatList.java.template", no_bool, "StatList")
  make("template/Function.java.template", all, "Function")
  
  File.delete("test.sh") if File.exist?("test.sh")
  all.each { |primitive|
   File.open("test.sh", "a") { |f|
      f.puts "echo #{primitive}"
      f.puts "java -cp lib/primitives.jar primitive.collection.#{primitive.capitalize}List"
    }

  }
  no_bool.each { |primitive|
    
   File.open("test.sh", "a") { |f|
      f.puts "echo #{primitive}"
      f.puts "java -cp lib/primitives.jar primitive.collection.#{primitive.capitalize}StatList"
    }
  }

end
