$random = {
   "byte"    => "(byte)rand.nextInt(256)",
   "short"   => "(short)rand.nextInt(32000)",
   "int"     => "rand.nextInt()",
   "long"    => "rand.nextLong()",
   "boolean" => "rand.nextBoolean()",
   "float"   => "rand.nextFloat()",
   "double"  => "rand.nextDouble()",
   "char"    => "(char)rand.nextInt()"

}

if $0 == __FILE__
  template = nil
  begin
    f        = File.open("template/List.java.template") 
    template = f.read
  ensure
    f.close if f
  end

  File.delete("test.sh") if File.exist?("test.sh")
  
  %w{
    byte
    short
    int
    long
    boolean
    float
    double
    char
  }.each {|primitive|
   
    n = template.gsub("<<Type>>"   , primitive)
    n =        n.gsub("<<Name>>"   , primitive.capitalize)
    n =        n.gsub("<<Warning>>", "/* DO NOT EDIT THIS FILE, IT IS GENERATED! */") 
    n =        n.gsub("<<Random>>" , $random[primitive])
    
    file_name = "src/java/primitive/collection/#{primitive.capitalize}List.java"

    File.open(file_name, "w") { |f|
      f.print(n)
    }

    File.open("test.sh", "a") { |f|
      f.puts "echo #{primitive}"
      f.puts "java -cp bin primitive.collection.#{primitive.capitalize}List"
    }
  }

end
