package primitive.collection;

/* DO NOT EDIT THIS FILE, IT IS GENERATED! */

public abstract class BooleanFunction {
  public void     apply(boolean value) {}
  public boolean accumulate(boolean memo, boolean value) {return false;}
} 
