package primitive.collection;

/* DO NOT EDIT THIS FILE, IT IS GENERATED! */

import java.util.Random;

public class DoubleStatList extends DoubleList {

  public void each (DoubleFunction func) {
    for(int i=0; i!=this.size(); ++i) {
      func.apply(this.get(i));
    }  
  }

  public double reduce(double initial, DoubleFunction func) {
    double memo = initial;
    for(int i=0; i!=this.size(); ++i) {
      memo = func.accumulate(memo, this.get(i));
    }
    return memo;
    
  } 

  public double sum () {
    DoubleFunction f = new DoubleFunction() {
      public double accumulate(double memo, double value) {
        return (double)(memo+value);
      }
    };

    return this.reduce((double)0,f);
  }

  public DoubleStats stats () {
    
    final DoubleStats stats = new DoubleStats();

    DoubleFunction f = new DoubleFunction() {
      public void apply(double value) {
        
        if (value < stats.min) {
          stats.min = value;
        } 
        if (value > stats.max) {
          stats.max = value;
        }
        stats.sum += value;
      }
    
    };
     
    this.each(f);
    
    stats.n   = this.size();
    stats.avg = stats.sum / (double)stats.n;
    
    f = new DoubleFunction() {
      public void apply(double value) {
        stats.var += Math.pow(stats.avg - (double)value, 2);
      }
    };
    
    this.each(f);

    stats.var  = stats.var / (double)stats.n;
    stats.stdd = Math.pow(stats.var, 0.5);
    return stats;

    
  }

  static DoubleStatList random(int count) {
    Random       rand = new Random(0L);
    DoubleStatList slist = new DoubleStatList();
    double value;
    for (int i=0; i!=count; ++i) {
      value = rand.nextDouble();
      slist.add(value);
    }
    return slist;
  }

  class DoubleStats {
    public int n;
    public double min = Double.MAX_VALUE;
    public double max = Double.MIN_VALUE;
    public double sum;
    public double avg;
    public double stdd;
    public double var;
    public String toString() {
      StringBuilder b = new StringBuilder();
      b.append("n    = "); b.append(n);   b.append("\n");
      b.append("min  = "); b.append(min); b.append("\n");
      b.append("max  = "); b.append(max); b.append("\n");
      b.append("sum  = "); b.append(sum); b.append("\n");
      b.append("avg  = "); b.append(avg); b.append("\n");
      b.append("stdd = "); b.append(stdd);b.append("\n");
      b.append("var  = "); b.append(var); b.append("\n");
      return b.toString();
    }
  }
  
  private static void p(Object o) {
    System.out.println(o);
  }
  public static void main (String [] args) {
    DoubleStatList list = DoubleStatList.random(10);
    
    list.each(new DoubleFunction() {
      public void apply(double value) {
        p(value);
      }
    });
    p(list.stats());
    p(list.sum());

    IntStatList l = new IntStatList();
    for (int i =1; i<101; ++i) {
      l.add(i);
    }
    p(l.stats());
    p(l.sum());
  }

}

