package primitive.collection;

/* DO NOT EDIT THIS FILE, IT IS GENERATED! */

public abstract class DoubleFunction {
  public void     apply(double value) {}
  public double accumulate(double memo, double value) {return 0.0d;}
} 
