package primitive.collection;

/* DO NOT EDIT THIS FILE, IT IS GENERATED! */

public abstract class FloatFunction {
  public void     apply(float value) {}
  public float accumulate(float memo, float value) {return 0.0f;}
} 
