package primitive.collection;

/* DO NOT EDIT THIS FILE, IT IS GENERATED! */

import java.util.Random;

public class IntStatList extends IntList {

  public void each (IntFunction func) {
    for(int i=0; i!=this.size(); ++i) {
      func.apply(this.get(i));
    }  
  }

  public int reduce(int initial, IntFunction func) {
    int memo = initial;
    for(int i=0; i!=this.size(); ++i) {
      memo = func.accumulate(memo, this.get(i));
    }
    return memo;
    
  } 

  public int sum () {
    IntFunction f = new IntFunction() {
      public int accumulate(int memo, int value) {
        return (int)(memo+value);
      }
    };

    return this.reduce((int)0,f);
  }

  public IntStats stats () {
    
    final IntStats stats = new IntStats();

    IntFunction f = new IntFunction() {
      public void apply(int value) {
        
        if (value < stats.min) {
          stats.min = value;
        } 
        if (value > stats.max) {
          stats.max = value;
        }
        stats.sum += value;
      }
    
    };
     
    this.each(f);
    
    stats.n   = this.size();
    stats.avg = stats.sum / (double)stats.n;
    
    f = new IntFunction() {
      public void apply(int value) {
        stats.var += Math.pow(stats.avg - (double)value, 2);
      }
    };
    
    this.each(f);

    stats.var  = stats.var / (double)stats.n;
    stats.stdd = Math.pow(stats.var, 0.5);
    return stats;

    
  }

  static IntStatList random(int count) {
    Random       rand = new Random(0L);
    IntStatList slist = new IntStatList();
    int value;
    for (int i=0; i!=count; ++i) {
      value = rand.nextInt();
      slist.add(value);
    }
    return slist;
  }

  class IntStats {
    public int n;
    public int min = Integer.MAX_VALUE;
    public int max = Integer.MIN_VALUE;
    public int sum;
    public double avg;
    public double stdd;
    public double var;
    public String toString() {
      StringBuilder b = new StringBuilder();
      b.append("n    = "); b.append(n);   b.append("\n");
      b.append("min  = "); b.append(min); b.append("\n");
      b.append("max  = "); b.append(max); b.append("\n");
      b.append("sum  = "); b.append(sum); b.append("\n");
      b.append("avg  = "); b.append(avg); b.append("\n");
      b.append("stdd = "); b.append(stdd);b.append("\n");
      b.append("var  = "); b.append(var); b.append("\n");
      return b.toString();
    }
  }
  
  private static void p(Object o) {
    System.out.println(o);
  }
  public static void main (String [] args) {
    IntStatList list = IntStatList.random(10);
    
    list.each(new IntFunction() {
      public void apply(int value) {
        p(value);
      }
    });
    p(list.stats());
    p(list.sum());

    IntStatList l = new IntStatList();
    for (int i =1; i<101; ++i) {
      l.add(i);
    }
    p(l.stats());
    p(l.sum());
  }

}

