package primitive.collection;

/* DO NOT EDIT THIS FILE, IT IS GENERATED! */

public abstract class LongFunction {
  public void     apply(long value) {}
  public long accumulate(long memo, long value) {return 0L;}
} 
